wizello/account/urls.py
from django.urls import path
from .views import (
    EmployeeListView, EmployeeDeactiveView, EmployeeRegisterView,
    EmployeeAdminListView, EmployeeAdminDeactiveView, EmployeeAdminUpdateView)

app_name = 'account'

urlpatterns = [
    # employee
    path('employee/', EmployeeListView.as_view(), name="employeelist"),
    path('employee/register/', EmployeeRegisterView.as_view(),
         name="employeeregister"),
    path('employee/deactive/<int:pk>/', EmployeeDeactiveView.as_view(),
         name="employeedeactive"),
    # admin
    path('employee/admin/', EmployeeAdminListView.as_view(),
         name="employeeadminlist"),
    path('employee/admin/deactive/<int:pk>/', EmployeeAdminDeactiveView.as_view(),
         name="employeeadmindeactive"),
    path('employee/admin/update/<int:pk>/', EmployeeAdminUpdateView.as_view(),
         name="employeeadminupdate"),
]

wizello/core/urls.py
from django.urls import path, include
from .views import (
    DashboardView,
    IndexView)

app_name = 'core'

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name="home"),
    path('', include('django.contrib.auth.urls')),
    path('', IndexView.as_view(), name="index"),
]

wizello/organization/urls.py
from django.urls import path, include
from .views import (
    OrganizationListView, OrganizationCreateView,
    OrganizationUpdateView, OrganizationDeleteView
)

app_name = 'organization'

urlpatterns = [
    path('', OrganizationListView.as_view(), name="organizationlist"),
    path('create/', OrganizationCreateView.as_view(), name="organizationcreate"),
    path('update/<int:pk>/', OrganizationUpdateView.as_view(),
         name="organizationupdate"),
    path('delete/<int:pk>/', OrganizationDeleteView.as_view(),
         name="organizationdelete"),
]

wizello/request/urls.py
from django.urls import path, include
from .views import (
    RequestManagerListView, RequestManagerAcceptView,
    RequestListView, RequestCreateView, RequestDeleteView,
    RequestAdminListView, RequestAdminAcceptView)

app_name = 'request'

urlpatterns = [
    # request
    path('', RequestListView.as_view(), name="requestlist"),
    path('create/', RequestCreateView.as_view(), name="requestcreate"),
    path('delete/<int:pk>/', RequestDeleteView.as_view(), name="requestdelete"),
    # Manager
    path('manager/', RequestManagerListView.as_view(), name="requestmanagerlist"),
    path('manager/accept/<int:pk>/',
         RequestManagerAcceptView.as_view(), name="requestaccept"),
    # Admin
    path('admin/', RequestAdminListView.as_view(), name="requestadminlist"),
    path('admin/accept/<int:pk>/',
         RequestAdminAcceptView.as_view(), name="requestadminaccept"),
]

wizello/task/urls.py
from django.urls import path, include
from .views import (
    TaskListView, TaskCreateView, TaskUpdateView, TaskDeleteView,
    TaskManagerListView, TaskManagerCreateView, TaskManagerUpdateView, TaskManagerDeleteView,
    TaskAdminListView, TaskAdminUpdateView, TaskAdminDeleteView)

app_name = 'task'

urlpatterns = [
    # task
    path('', TaskListView.as_view(), name="tasklist"),
    path('create/', TaskCreateView.as_view(), name="taskcreate"),
    path('edit/<int:pk>/', TaskUpdateView.as_view(), name="taskupdate"),
    path('delete/<int:pk>/', TaskDeleteView.as_view(), name="taskdelete"),
    # manager
    path('manager/', TaskManagerListView.as_view(), name="taskmanagerlist"),
    path('manager/create/', TaskManagerCreateView.as_view(),
         name="taskmanagercreate"),
    path('manager/edit/<int:pk>/', TaskManagerUpdateView.as_view(),
         name="taskmanagerupdate"),
    path('manager/delete/<int:pk>/',
         TaskManagerDeleteView.as_view(), name="taskmanagerdelete"),
    # admin
    path('admin/', TaskAdminListView.as_view(), name="taskadminlist"),
    path('admin/edit/<int:pk>/', TaskAdminUpdateView.as_view(),
         name="taskadminupdate"),
    path('admin/delete/<int:pk>/',
         TaskAdminDeleteView.as_view(), name="taskadmindelete"),
]

wizello/wizello/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('task/', include('task.urls')),
    path('request/', include('request.urls')),
    path('account/', include('account.urls')),
    path('organization/', include('organization.urls')),

    # API
    path('api/organization/', include('organization.api.urls')),
    path('api/employee/', include('account.api.urls')),
    path('api/task/', include('task.api.urls')),
    path('api/request/', include('request.api.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wizello/core/models.py
from django.db import models


class BaseModel(models.Model):
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

wizello/core/views.py
from django.views.generic import TemplateView, FormView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "core/dashboard.html"


class IndexView(TemplateView):
    template_name = "core/index.html"

wizello/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
  <meta name="author" content="Creative Tim">
  <title>{% block title %}{% endblock title %}</title> <!-- Favicon -->
  <link href="{% static 'core/img/brand/favicon.png' %}" rel="icon" type="image/png">
  <!-- Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <!-- Icons -->
  <link href="{% static 'core/vendor/nucleo/css/nucleo.css' %}" rel="stylesheet">
  <link href="{% static 'core/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <!-- IranSansFont -->
  <link type="text/css" href="{% static 'core/css/font.css' %}" rel="stylesheet">
  <!-- Argon CSS -->
  <link type="text/css" href="{% static 'core/css/argon.css' %}" rel="stylesheet"> 
  <!-- Bootstrap -->
  <link href="{% static 'core/vendor/bootstrap/dist/css/tempusdominus-bootstrap-4.css' %}" rel="stylesheet">    
</head>

<body>
    {% include "core/sidebar.html" %}
  <!-- Main content -->
  <div class="main-content">

    <!-- Header -->
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
      <div class="container-fluid">
        <div class="header-body">
		
        {% include "core/topnav.html" with pagename=request.user.employee.get_position_display %}
		    {% include "core/card.html" %}

		
        </div>
      </div>
    </div>

    <!-- Page content -->
    <div class="container-fluid mt--7">
	
	<!-- Content -->
		<div class="row">
			<div class="col">
				<div class="card shadow">
            {% block content %}
            {% endblock content %}
				</div>
			</div>
		</div>
	<!-- End Content -->

	
      <!-- Footer -->
      <footer class="footer">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="copyright text-center text-xl-left text-muted">
              &copy; 2018 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
            </div>
          </div>
          <div class="col-xl-6">
            <ul class="nav nav-footer justify-content-center justify-content-xl-end">
              <li class="nav-item">
                <a href="https://www.creative-tim.com" class="nav-link" target="_blank">Creative Tim</a>
              </li>
              <li class="nav-item">
                <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
              </li>
              <li class="nav-item">
                <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
              </li>
              <li class="nav-item">
                <a href="https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md" class="nav-link" target="_blank">MIT License</a>
              </li>
            </ul>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!-- Argon Scripts -->
  <!-- Core -->
  <script src="{% static 'core/vendor/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'core/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'core/vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'core/vendor/bootstrap-datepicker/dist/js/moment.js' %}"></script>  
  <script src="{% static 'core/vendor/bootstrap/dist/js/tempusdominus-bootstrap-4.js' %}"></script>  
  
  <!-- Optional JS -->
  <script src="{% static 'core/vendor/chart.js/dist/Chart.min.js' %}"></script>
  <script src="{% static 'core/vendor/chart.js/dist/Chart.extension.js' %}"></script>
  <!-- Argon JS -->
  <script src="{% static 'core/js/argon.js?v=1.0.0' %}"></script>
        <script type="text/javascript">
          $(function () {
              $('#datetimepicker1').datetimepicker({
                format: 'YYYY-MM-DD hh:mm:ss'
              });       
          });
        </script>  
</body>

</html>

wizello/core/templates/core/card.html
{% load static %}
<!-- Card stats -->
<div class="row">
<div class="col-xl-3 col-lg-6">
    <div class="card card-stats mb-4 mb-xl-0">
    <div class="card-body">
        <div class="row">
        <div class="col">
            <h5 class="card-title text-uppercase text-muted mb-0">Requests</h5>
            <span class="h2 font-weight-bold mb-0">350,890</span>
        </div>
        <div class="col-auto">
            <div class="icon icon-shape bg-danger text-white rounded-circle shadow">
            <i class="fas fa-chart-bar"></i>
            </div>
        </div>
        </div>
        <p class="mt-3 mb-0 text-muted text-sm">
        <span class="text-success mr-2"><i class="fa fa-arrow-up"></i>3.52%</span>
        <span class="text-nowrap">Since Last Month</span>
        </p>
    </div>
    </div>
</div>
<div class="col-xl-3 col-lg-6">
    <div class="card card-stats mb-4 mb-xl-0">
    <div class="card-body">
        <div class="row">
        <div class="col">
            <h5 class="card-title text-uppercase text-muted mb-0">New Employee</h5>
            <span class="h2 font-weight-bold mb-0">25</span>
        </div>
        <div class="col-auto">
            <div class="icon icon-shape bg-warning text-white rounded-circle shadow">
            <i class="fas fa-chart-pie"></i>
            </div>
        </div>
        </div>
        <p class="mt-3 mb-0 text-muted text-sm">
        <span class="text-danger mr-2"><i class="fas fa-arrow-down"></i>3.52%</span>
        <span class="text-nowrap">Since last week</span>
        </p>
    </div>
    </div>
</div>
<div class="col-xl-3 col-lg-6">
    <div class="card card-stats mb-4 mb-xl-0">
    <div class="card-body">
        <div class="row">
        <div class="col">
            <h5 class="card-title text-uppercase text-muted mb-0">Tasks</h5>
            <span class="h2 font-weight-bold mb-0">925</span>
        </div>
        <div class="col-auto">
            <div class="icon icon-shape bg-yellow text-white rounded-circle shadow">
            <i class="fas fa-users"></i>
            </div>
        </div>
        </div>
        <p class="mt-3 mb-0 text-muted text-sm">
        <span class="text-warning mr-2"><i class="fas fa-arrow-down"></i>1.10%</span>
        <span class="text-nowrap">Since yesterday</span>
        </p>
    </div>
    </div>
</div>
<div class="col-xl-3 col-lg-6">
    <div class="card card-stats mb-4 mb-xl-0">
    <div class="card-body">
        <div class="row">
        <div class="col">
            <h5 class="card-title text-uppercase text-muted mb-0">year</h5>
            <span class="h2 font-weight-bold mb-0">1398</span>
        </div>
        <div class="col-auto">
            <div class="icon icon-shape bg-info text-white rounded-circle shadow">
            <i class="fas fa-percent"></i>
            </div>
        </div>
        </div>
        <p class="mt-3 mb-0 text-muted text-sm">
        <span class="text-success mr-2"><i class="fas fa-arrow-up"></i>50%</span>
        <span class="text-nowrap">Since last year</span>
        </p>
    </div>
    </div>
</div>
</div>

wizello/core/templates/core/confirm_delete.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Wizello Dashboard{% endblock title %}

{% block content %}
<div class="card-header bg-transparent">
    <h3 class="mb-0">Delete</h3>
</div>
<div class="card-body">
    <form method="post">{% csrf_token %}
        <p>do you want to delete? ( {{ object }} ) ?</p>
        <input type="submit" class="btn btn-warning" value="Delete">
    </form>
</div>
{% endblock content %}

wizello/core/templates/core/dashboard.html
{% extends "core/base.html" %}
{% block title %}Wizello Dashboard{% endblock title %}
{% block content %}
<div class="card-header bg-transparent">
    <h3 class="mb-0">Dashboard</h3>
</div>
<div class="card-body">
</div>
{% endblock content %}

wizello/core/templates/core/formcreate.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card-header bg-transparent">
    <h3 class="mb-0">CRUD</h3>
</div>
<div class="card-body">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form|crispy }}
    <input type="hidden" name="user" value="{{request.user.id}}" /><br>
    <button type="submit" class="btn btn-success">Save</button>
  </form>
</div>
{% endblock content %}

wizello/core/templates/core/index.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
  <meta name="author" content="Creative Tim">
  <title>Wizello Login</title>
  <!-- Favicon -->
  <link href="{% static 'core/img/brand/favicon.png' %}" rel="icon" type="image/png">
  <!-- Fonts -->
  <!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet"> -->
  <!-- Icons -->
  <link href="{% static 'core/vendor/nucleo/css/nucleo.css' %}" rel="stylesheet">
  <link href="{% static 'core/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <!-- Argon CSS -->
  <link type="text/css" href="{% static 'core/css/argon.css' %}" rel="stylesheet"> 
</head>

<body class="bg-default">
  <div class="main-content">
    <!-- Navbar -->
    <nav class="navbar navbar-top navbar-horizontal navbar-expand-md navbar-dark">
      <div class="container px-4">
        <a class="navbar-brand" href="../index.html">
          <img src="{% static 'core/img/brand/white.png' %}" />
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-collapse-main">
          <!-- Collapse header -->
          <div class="navbar-collapse-header d-md-none">
            <div class="row">
              <div class="col-6 collapse-brand">
                <a href="../index.html">
                  <img src="../assets/img/brand/blue.png">
                </a>
              </div>
              <div class="col-6 collapse-close">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                  <span></span>
                  <span></span>
                </button>
              </div>
            </div>
          </div>
          <!-- Navbar items -->
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link nav-link-icon" href="{% url 'account:employeeregister' %}">
                <i class="ni ni-circle-08"></i>
                <span class="nav-link-inner--text">Register Employee</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-link-icon" href="{% url 'core:login' %}">
                <i class="ni ni-key-25"></i>
                <span class="nav-link-inner--text">Login</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Header -->
    <div class="header bg-gradient-primary py-7 py-lg-8">
      <div class="container">
        <div class="header-body text-center mb-7">
          <div class="row justify-content-center">
            <div class="col-lg-5 col-md-6">
              <h1 class="text-white"></h1>
            </div>
          </div>
        </div>
      </div>
      <div class="separator separator-bottom separator-skew zindex-100">
        <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
          <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
        </svg>
      </div>
    </div>
    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-body px-lg-3 py-lg-4">
            <h1> Wizello </h1>
            <h2>Developed by Sajjad Hassanzadeh</h2>
            <h3>09378228100</h3>
            <h3>hassanzadeh.sd@gmail.com</h3>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
  <!-- Footer -->
  <footer class="py-5">
    <div class="container">
      <div class="row align-items-center justify-content-xl-between">
        <div class="col-xl-6">
          <div class="copyright text-center text-xl-left text-muted">
            &copy; 2018 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
          </div>
        </div>
        <div class="col-xl-6">
          <ul class="nav nav-footer justify-content-center justify-content-xl-end">
            <li class="nav-item">
              <a href="#" class="nav-link" target="_blank">Creative Tim</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link" target="_blank">About Us</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link" target="_blank">Blog</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link" target="_blank">MIT License</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  <!-- Argon Scripts -->
  <!-- Core -->
  <script src="../assets/vendor/jquery/dist/jquery.min.js"></script>
  <script src="../assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Argon JS -->
  <script src="../assets/js/argon.js?v=1.0.0"></script>
</body>

</html>

wizello/core/templates/core/sidebar.html
{% load static %}
  <!-- Sidenav -->
  <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
      <!-- Toggler -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Brand -->
      <a class="navbar-brand pt-0" href="#">
        <img src="{% static 'core/img/brand/blue.png' %}" class="navbar-brand-img" alt="...">
      </a>
      <!-- User -->
      <ul class="nav align-items-center d-md-none">
        <li class="nav-item dropdown">
          <a class="nav-link nav-link-icon" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-bell-55"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-left" aria-labelledby="navbar-default_dropdown_1">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <img alt="Image placeholder" src="{% static 'core/img/theme/team-1-800x800.jpg' %}">
              </span>
            </div>
          </a>
          <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-left">
            <div class=" dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a href="./examples/profile.html" class="dropdown-item">
              <i class="ni ni-single-02"></i>
              <span>My profile</span>
            </a>
            <a href="./examples/profile.html" class="dropdown-item">
              <i class="ni ni-settings-gear-65"></i>
              <span>Settings</span>
            </a>
            <a href="./examples/profile.html" class="dropdown-item">
              <i class="ni ni-calendar-grid-58"></i>
              <span>Activity</span>
            </a>
            <a href="./examples/profile.html" class="dropdown-item">
              <i class="ni ni-support-16"></i>
              <span>Support</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'core:logout' %}" class="dropdown-item">
              <i class="ni ni-user-run"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
      </ul>
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Collapse header -->
        <div class="navbar-collapse-header d-md-none">
          <div class="row">
            <div class="col-6 collapse-brand">
              <a href="./index.html">
                <img src="{% static 'core/img/brand/blue.png' %}">
              </a>
            </div>
            <div class="col-6 collapse-close">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                <span></span>
                <span></span>
              </button>
            </div>
          </div>
        </div>
        <!-- Form -->
        <form class="mt-4 mb-3 d-md-none">
          <div class="input-group input-group-rounded input-group-merge">
            <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="Search" aria-label="Search">
            <div class="input-group-prepend">
              <div class="input-group-text">
                <span class="fa fa-search"></span>
              </div>
            </div>
          </div>
        </form>
        <!-- Navigation -->
        <h6 class="navbar-heading text-muted">Dashboard</h6>
        <ul class="navbar-nav">
        <hr class="my-3">
          <li class="nav-item">
            {% if request.user.employee.position == "M" %}
            <a class="nav-link" href="{% url 'task:taskmanagerlist' %}">
              <i class="ni ni-bell-55 text-yellow"></i> Organization Task
            </a>            
            <a class="nav-link" href="{% url 'request:requestmanagerlist' %}">
              <i class="ni ni-box-2 text-info"></i> Employee Requests
            </a>                               
            <a class="nav-link" href="{% url 'account:employeelist' %}">
              <i class="ni ni-circle-08 text-danger"></i> Employees List
            </a>            
            <a class="nav-link" href="{% url 'request:requestlist' %}">
              <i class="ni ni-archive-2 text-info"></i> My Requests
            </a>            
            {% elif user.is_superuser %}
            <a class="nav-link" href="{% url 'request:requestadminlist' %}">
              <i class="ni ni-box-2 text-info"></i> Request Admin
            </a>                           
            <a class="nav-link" href="{% url 'account:employeeadminlist' %}">
              <i class="ni ni-circle-08 text-danger"></i> Employees List
            </a>                                       
            <a class="nav-link" href="{% url 'organization:organizationlist' %}">
              <i class="ni ni-folder-17 text-blue"></i> Organization
            </a> 
            <a class="nav-link" href="{% url 'task:taskadminlist' %}">
              <i class="ni ni-bell-55 text-yellow"></i> Tasks
            </a>                                                               
            {% else %}
            <a class="nav-link" href="{% url 'request:requestlist' %}">
              <i class="ni ni-archive-2 text-info"></i> Requests
            </a>
            <a class="nav-link" href="{% url 'task:tasklist' %}">
              <i class="ni ni-bell-55 text-yellow"></i> Tasks
            </a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>

wizello/core/templates/core/topnav.html
{% load static %}
<!-- Top navbar -->
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
    <!-- Brand -->
    <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="#">{% if pagename %}{{pagename}}{% endif %}</a>
    <!-- Form -->
    <form class="navbar-search navbar-search-dark form-inline mr-3 d-none d-md-flex ml-lg-auto">
        <div class="form-group mb-0">
        <div class="input-group input-group-alternative">
            <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-search"></i></span>
            </div>
            <input class="form-control" placeholder="Search" type="text">
        </div>
        </div>
    </form>
    <!-- User -->
    <ul class="navbar-nav align-items-center d-none d-md-flex">
        <li class="nav-item dropdown">
        <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
            <span class="avatar avatar-sm rounded-circle">
                <img alt="Image placeholder" src="{% static 'core/img/theme/team-4-800x800.jpg' %}">
            </span>            
            <div class="media-body ml-2 d-none d-lg-block">
                <a href="{% url 'core:logout' %}">
                <span class="mb-0 text-sm p-4 font-weight-bold text-white">Logout</span>
                </a>                
            </div>
            </div>
        </a>
        </li>
    </ul>
    </div>
</nav>