wizello/core/urls.py
from django.urls import path, include
from .views import (
    DashboardView,
    IndexView)

app_name = 'core'

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name="home"),
    path('', include('django.contrib.auth.urls')),
    path('', IndexView.as_view(), name="index"),
]

wizello/organization/api/urls.py
from django.urls import path
from .views import (
    OrganizationListAPIView,
    OrganizationCreateAPIView,
    OrganizationUpdateAPIView,
    OrganizationDeleteAPIView,)

urlpatterns = [
    path('', OrganizationListAPIView.as_view(), name="organizationlistAPI"),
    path('create/', OrganizationCreateAPIView.as_view(),
         name="organizationcreateAPI"),
    path('update/<int:pk>/', OrganizationUpdateAPIView.as_view(),
         name="organizationupdateAPI"),
    path('delete/<int:pk>/', OrganizationDeleteAPIView.as_view(),
         name="organizationdeleteAPI"),
]

wizello/organization/urls.py
from django.urls import path, include
from .views import (
    OrganizationListView, OrganizationCreateView,
    OrganizationUpdateView, OrganizationDeleteView
)

app_name = 'organization'

urlpatterns = [
    path('', OrganizationListView.as_view(), name="organizationlist"),
    path('create/', OrganizationCreateView.as_view(), name="organizationcreate"),
    path('update/<int:pk>/', OrganizationUpdateView.as_view(),
         name="organizationupdate"),
    path('delete/<int:pk>/', OrganizationDeleteView.as_view(),
         name="organizationdelete"),
]

wizello/wizello/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('task/', include('task.urls')),
    path('request/', include('request.urls')),
    path('account/', include('account.urls')),
    path('organization/', include('organization.urls')),

    # API
    path('api/organization/', include('organization.api.urls')),
    path('api/employee/', include('account.api.urls')),
    path('api/task/', include('task.api.urls')),
    path('api/request/', include('request.api.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wizello/organization/models.py
from core.models import BaseModel, models


class Organization(BaseModel):
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name = "Organization"
        verbose_name_plural = "Organizations"
        ordering = ['-created']

    def __str__(self):
        return self.name

    def get_employeesCount(self):
        return str(self.employee.count())

wizello/organization/api/views.py
from rest_framework import generics
from django.db.models import Q
from rest_framework import permissions
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import OrganizationModelSerializer
from ..models import Organization


class OrganizationListAPIView(generics.ListAPIView):
    queryset = Organization.objects.all()
    serializer_class = OrganizationModelSerializer
    permission_classes = [permissions.IsAdminUser]


class OrganizationCreateAPIView(generics.CreateAPIView):
    serializer_class = OrganizationModelSerializer
    permission_classes = [permissions.IsAdminUser]


class OrganizationUpdateAPIView(generics.UpdateAPIView):
    queryset = Organization.objects.all()
    serializer_class = OrganizationModelSerializer
    permission_classes = [permissions.IsAdminUser]


class OrganizationDeleteAPIView(generics.DestroyAPIView):
    queryset = Organization.objects.all()
    serializer_class = OrganizationModelSerializer
    permission_classes = [permissions.IsAdminUser]

wizello/organization/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Organization

# -------------------- Organization


class OrganizationListView(LoginRequiredMixin, ListView):
    model = Organization
    context_object_name = "organizations"
    template_name = "organization/organizationlist.html"


class OrganizationCreateView(LoginRequiredMixin, CreateView):
    model = Organization
    fields = ('__all__')
    template_name = "core/formcreate.html"
    success_url = reverse_lazy("organization:organizationlist")


class OrganizationUpdateView(LoginRequiredMixin, UpdateView):
    model = Organization
    fields = ('__all__')
    template_name = "core/formcreate.html"
    success_url = reverse_lazy("organization:organizationlist")


class OrganizationDeleteView(LoginRequiredMixin, DeleteView):
    model = Organization
    template_name = "core/confirm_delete.html"
    success_url = reverse_lazy("organization:organizationlist")

wizello/organization/templates/organization/organizationlist.html
{% extends "core/base.html" %}

{% block title %}Organization{% endblock title %}

{% block content %}
<div class="card-header bg-transparent d-inline">
    <a href="{% url 'organization:organizationcreate' %}" class="btn btn-info">Create New Organization</a>
</div>
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Employees</th>
                    <th scope="col">ACT</th>
                  </tr>
                </thead>
                <tbody>

{% for obj_organization in organizations %}
    
                  <tr>
                    <th scope="row">
                        <span>{{obj_organization.id}}</span>
                    </th>
                    <th scope="row">
                        <span>{{obj_organization.name}}</span>
                    </th>
                    <td>
                        <span>{{obj_organization.get_employeesCount}}</span>
                    </td>                 
                    <td>
                        <a href="{% url 'organization:organizationupdate' obj_organization.id %}">Edit</a> /
                        <a href="{% url 'organization:organizationdelete' obj_organization.id %}">Delete</a>
                    </td>
                  </tr>
{% endfor %}
                </tbody>
              </table>
            </div>
{% endblock content %}