wizello/core/urls.py
from django.urls import path, include
from .views import (
    DashboardView,
    IndexView)

app_name = 'core'

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name="home"),
    path('', include('django.contrib.auth.urls')),
    path('', IndexView.as_view(), name="index"),
]

wizello/task/api/urls.py
from django.urls import path
from .views import (
    TaskListAPIView,
    TaskUpdateAPIView,
    TaskDeleteAPIView,
)

urlpatterns = [
    path('', TaskListAPIView.as_view(), name="tasklistAPI"),
    path('update/<int:pk>/', TaskUpdateAPIView.as_view(),
         name="taskupdateAPI"),
    path('delete/<int:pk>/', TaskDeleteAPIView.as_view(),
         name="taskdeleteAPI"),
]

wizello/task/urls.py
from django.urls import path, include
from .views import (
    TaskListView, TaskCreateView, TaskUpdateView, TaskDeleteView,
    TaskManagerListView, TaskManagerCreateView, TaskManagerUpdateView, TaskManagerDeleteView,
    TaskAdminListView, TaskAdminUpdateView, TaskAdminDeleteView)

app_name = 'task'

urlpatterns = [
    # task
    path('', TaskListView.as_view(), name="tasklist"),
    path('create/', TaskCreateView.as_view(), name="taskcreate"),
    path('edit/<int:pk>/', TaskUpdateView.as_view(), name="taskupdate"),
    path('delete/<int:pk>/', TaskDeleteView.as_view(), name="taskdelete"),
    # manager
    path('manager/', TaskManagerListView.as_view(), name="taskmanagerlist"),
    path('manager/create/', TaskManagerCreateView.as_view(),
         name="taskmanagercreate"),
    path('manager/edit/<int:pk>/', TaskManagerUpdateView.as_view(),
         name="taskmanagerupdate"),
    path('manager/delete/<int:pk>/',
         TaskManagerDeleteView.as_view(), name="taskmanagerdelete"),
    # admin
    path('admin/', TaskAdminListView.as_view(), name="taskadminlist"),
    path('admin/edit/<int:pk>/', TaskAdminUpdateView.as_view(),
         name="taskadminupdate"),
    path('admin/delete/<int:pk>/',
         TaskAdminDeleteView.as_view(), name="taskadmindelete"),
]

wizello/wizello/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('task/', include('task.urls')),
    path('request/', include('request.urls')),
    path('account/', include('account.urls')),
    path('organization/', include('organization.urls')),

    # API
    path('api/organization/', include('organization.api.urls')),
    path('api/employee/', include('account.api.urls')),
    path('api/task/', include('task.api.urls')),
    path('api/request/', include('request.api.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wizello/task/models.py
from core.models import BaseModel, models
from django.contrib.auth.models import User


class Task(BaseModel):
    subject = models.CharField(max_length=200)
    description = models.TextField(max_length=400)
    deadline = models.DateTimeField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    assignee = models.ManyToManyField(User, related_name='taskassignee')

    class Meta:
        verbose_name = "Task"
        verbose_name_plural = "Tasks"
        ordering = ['deadline']

    def __str__(self):
        return self.subject

    def get_assignee(self):
        assigneeNames = ""
        for objAssignee in self.assignee.all():
            assigneeNames += objAssignee.username + " , "
        return assigneeNames

wizello/task/forms.py
from django import forms
from .models import Task
from account.models import Employee


class TaskManagerForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            'subject',
            'description',
            'deadline',
            'assignee',
        ]

    def __init__(self, *args, **kwargs):
        super(TaskManagerForm, self).__init__(*args, **kwargs)
        self.fields['deadline'].widget.attrs['class'] = 'datepicker'

wizello/task/api/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404
from rest_framework import generics
from rest_framework import permissions
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import TaskModelSerializer, TaskUpdateModelSerializer
from ..models import Task


class TaskListAPIView(generics.ListAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskModelSerializer
    permission_classes = [permissions.IsAdminUser]


class TaskUpdateAPIView(generics.UpdateAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskUpdateModelSerializer
    permission_classes = [permissions.IsAdminUser]


class TaskDeleteAPIView(generics.DestroyAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskModelSerializer
    permission_classes = [permissions.IsAdminUser]

wizello/task/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, View, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.urls import reverse_lazy
from .models import Task, User
from account.models import Employee
from .forms import TaskManagerForm
# -------------------- Task List


class TaskListView(LoginRequiredMixin, ListView):
    context_object_name = "tasks"
    template_name = "task/tasklist.html"

    def get_queryset(self):
        qs = self.request.user.taskassignee.all()
        return qs


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    fields = ('subject', 'description', 'deadline')
    template_name = "task/employeecreateform.html"
    success_url = reverse_lazy("task:tasklist")

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()
        self.object.assignee.add(self.request.user)
        return HttpResponseRedirect(self.get_success_url())


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ('subject', 'description', 'deadline')
    template_name = "core/formcreate.html"
    success_url = reverse_lazy("task:tasklist")


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = "core/confirm_delete.html"
    success_url = reverse_lazy("task:tasklist")


# -------------------- Task Manager List

class TaskManagerListView(LoginRequiredMixin, ListView):
    context_object_name = "tasks"
    template_name = "task/taskmanagerlist.html"

    def get_queryset(self):
        organization = self.request.user.employee.organization
        qs = Task.objects.filter(assignee__employee__organization=organization)
        return qs


class TaskManagerCreateView(LoginRequiredMixin, FormView):
    form_class = TaskManagerForm
    template_name = "task/managercreateform.html"
    success_url = reverse_lazy("task:taskmanagerlist")

    def get_context_data(self, **kwargs):
        context = super(TaskManagerCreateView, self).get_context_data(**kwargs)
        managerAssigneeChoices = []
        organization = self.request.user.employee.organization
        for objEmployee in Employee.objects.filter(organization=organization):
            managerAssigneeChoices.append(dict(key=objEmployee.user.id, value=objEmployee.user.username)
                                          )
        context['managerAssigneeChoices'] = managerAssigneeChoices
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()

        assignee = form.cleaned_data['assignee']
        user_list = User.objects.filter(pk__in=assignee)
        for objuser in user_list:
            self.object.assignee.add(objuser)

        return HttpResponseRedirect(self.get_success_url())


class TaskManagerUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ('deadline', 'assignee')
    template_name = "core/formcreate.html"
    success_url = reverse_lazy("task:taskmanagerlist")


class TaskManagerDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = "core/confirm_delete.html"
    success_url = reverse_lazy("task:taskmanagerlist")


# -------------------- Task Admin List

class TaskAdminListView(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "task/taskadminlist.html"


class TaskAdminUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ('deadline', 'assignee')
    template_name = "core/formcreate.html"
    success_url = reverse_lazy("task:taskadminlist")


class TaskAdminDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = "core/confirm_delete.html"
    success_url = reverse_lazy("task:taskadminlist")

wizello/task/templates/task/createform.html
{% extends "core/base.html" %}

{% block content %}
<div class="card-header bg-transparent">
    <h3 class="mb-0">Create Task</h3>
</div>
<div class="card-body">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}


<div id="div_id_subject" class="form-group"> 
<label for="id_subject" class="col-form-label  requiredField">
Subject<span class="asteriskField">*</span> </label> <div class="">
<input type="text" name="subject" maxlength="200" class="textinput textInput form-control" required id="id_subject">
</div>
</div>
<div id="div_id_description" class="form-group">
<label for="id_description" class="col-form-label  requiredField">
Description<span class="asteriskField">*</span>
</label>
<div class="">
    <textarea name="description" cols="40" rows="10" maxlength="400" class="textarea form-control" required id="id_description"></textarea>
</div>
</div>
    <div id="div_id_deadline" class="form-group">
        <label for="id_deadline" class="col-form-label  requiredField">
            Deadline<span class="asteriskField">*</span>
        </label>
        <div class="form-group">
            <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                <input type="text" placeholder="YYYY-MM-DD hh:mm:ss" name="deadline" class="datetimepicker-input" data-target="#datetimepicker1"/>
                <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
            </div>
        </div>
    </div>
    <div id="div_id_assignee" class="form-group">
        <label for="id_assignee" class="col-form-label  requiredField">
            Assignee<span class="asteriskField">*</span> 
        </label> 
        <div class="">
            <select name="assignee" class="selectmultiple form-control" required id="id_assignee" multiple> 
            {% for objAssignee in managerAssigneeChoices %}
                <option value="{{objAssignee.key}}">{{objAssignee.value}}</option> 
            {% endfor %}
            </select> 
        </div> 
    </div>

    <input type="hidden" name="user" value="{{request.user.id}}" /><br>
    <button type="submit" class="btn btn-success">Save</button>
  </form>
</div>
{% endblock content %}

wizello/task/templates/task/employeecreateform.html
{% extends "core/base.html" %}

{% block content %}
<div class="card-header bg-transparent">
    <h3 class="mb-0">Create Task</h3>
</div>
<div class="card-body">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}


<div id="div_id_subject" class="form-group"> 
<label for="id_subject" class="col-form-label  requiredField">
Subject<span class="asteriskField">*</span> </label> <div class="">
<input type="text" name="subject" maxlength="200" class="textinput textInput form-control" required id="id_subject">
</div>
</div>
<div id="div_id_description" class="form-group">
<label for="id_description" class="col-form-label  requiredField">
Description<span class="asteriskField">*</span>
</label>
<div class="">
    <textarea name="description" cols="40" rows="10" maxlength="400" class="textarea form-control" required id="id_description"></textarea>
</div>
</div>
    <div id="div_id_deadline" class="form-group">
        <label for="id_deadline" class="col-form-label  requiredField">
            Deadline<span class="asteriskField">*</span>
        </label>
        <div class="form-group">
            <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                <input type="text" placeholder="YYYY-MM-DD hh:mm:ss" required id="id_deadline" name="deadline" class="datetimepicker-input" data-target="#datetimepicker1"/>
                <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-success">Save</button>
  </form>
</div>
{% endblock content %}

wizello/task/templates/task/managercreateform.html
{% extends "core/base.html" %}

{% block content %}
<div class="card-header bg-transparent">
    <h3 class="mb-0">Create Task</h3>
</div>
<div class="card-body">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}


<div id="div_id_subject" class="form-group"> 
<label for="id_subject" class="col-form-label  requiredField">
Subject<span class="asteriskField">*</span> </label> <div class="">
<input type="text" name="subject" maxlength="200" class="textinput textInput form-control" required id="id_subject">
</div>
</div>
<div id="div_id_description" class="form-group">
<label for="id_description" class="col-form-label  requiredField">
Description<span class="asteriskField">*</span>
</label>
<div class="">
    <textarea name="description" cols="40" rows="10" maxlength="400" class="textarea form-control" required id="id_description"></textarea>
</div>
</div>
    <div id="div_id_deadline" class="form-group">
        <label for="id_deadline" class="col-form-label  requiredField">
            Deadline<span class="asteriskField">*</span>
        </label>
        <div class="form-group">
            <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                <input type="text" placeholder="YYYY-MM-DD hh:mm:ss" required id="id_deadline" name="deadline" class="datetimepicker-input" data-target="#datetimepicker1"/>
                <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
            </div>
        </div>
    </div>
    <div id="div_id_assignee" class="form-group">
        <label for="id_assignee" class="col-form-label  requiredField">
            Assignee<span class="asteriskField">*</span> 
        </label> 
        <div class="">
            <select name="assignee" class="selectmultiple form-control" required id="id_assignee" multiple> 
            {% for objAssignee in managerAssigneeChoices %}
                <option value="{{objAssignee.key}}">{{objAssignee.value}}</option> 
            {% endfor %}
            </select> 
        </div> 
    </div>

    <input type="hidden" name="user" value="{{request.user.id}}" /><br>
    <button type="submit" class="btn btn-success">Save</button>
  </form>
</div>
{% endblock content %}

wizello/task/templates/task/taskadminlist.html
{% extends "core/base.html" %}

{% block title %}Tasks{% endblock title %}

{% block content %}
<div class="card-header bg-transparent d-inline">
</div>
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Owner</th>
                    <th scope="col">Act</th>
                  </tr>
                </thead>
                <tbody>

{% for obj_task in tasks %}
    
                  <tr>
                    <th scope="row">
                        <span>{{obj_task.id}}</span>
                    </th>
                    <th scope="row">
                        <span>{{obj_task.subject}}</span>
                    </th>
                    <td>
                        <span>{{obj_task.owner.username}}</span>
                    </td>
                    <td>
                        <div>
                            <a href="{% url 'task:taskadminupdate' obj_task.id %}">Edit</a> / 
                            <a href="{% url 'task:taskadmindelete' obj_task.id %}">Delete</a>
                        </div>
                    </td>                   
                  </tr>
{% endfor %}
                </tbody>
              </table>
            </div>
{% endblock content %}

wizello/task/templates/task/tasklist.html
{% extends "core/base.html" %}

{% block title %}Tasks{% endblock title %}

{% block content %}
<div class="card-header bg-transparent d-inline">
    <a href="{% url 'task:taskcreate' %}" class="btn btn-info">Create New Task</a>
</div>
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Owner</th>
                    <th scope="col">Act</th>
                  </tr>
                </thead>
                <tbody>

{% for obj_task in tasks %}
    
                  <tr>
                    <th scope="row">
                        <span>{{obj_task.id}}</span>
                    </th>
                    <th scope="row">
                        <span>{{obj_task.subject}}</span>
                    </th>
                    <td>
                        <span>{{obj_task.owner.username}}</span>
                    </td>
                    {% if obj_task.owner == request.user %}
                    <td>
                        <div>
                            <a href="{% url 'task:taskupdate' obj_task.id %}">Edit</a> / 
                            <a href="{% url 'task:taskdelete' obj_task.id %}">Delete</a>
                        </div>
                    </td>                   
                    {% else %}
                    <td>
                        <div>
                          <span>-</span>
                        </div>
                    </td>     
                    {% endif %}                
                  </tr>
{% endfor %}
                </tbody>
              </table>
            </div>
{% endblock content %}

wizello/task/templates/task/taskmanagerlist.html
{% extends "core/base.html" %}

{% block title %}Organization Tasks{% endblock title %}

{% block content %}
<div class="card-header bg-transparent d-inline">
    <a href="{% url 'task:taskmanagercreate' %}" class="btn btn-info">Create New Task</a>
</div>
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Owner</th>
                    <th scope="col">Assignee</th>
                    <th scope="col">Act</th>
                  </tr>
                </thead>
                <tbody>

{% for obj_task in tasks %}
    
                  <tr>
                    <th scope="row">
                        <span>{{obj_task.id}}</span>
                    </th>
                    <th scope="row">
                        <span>{{obj_task.subject}}</span>
                    </th>
                    <td>
                        <span>{{obj_task.owner.username}}</span>
                    </td>
                    <td>
                        <span>{{obj_task.get_assignee}}</span>
                    </td>                    
                    <td>
                        <div>
                            <a href="{% url 'task:taskmanagerupdate' obj_task.id %}">Edit</a> / 
                            <a href="{% url 'task:taskmanagerdelete' obj_task.id %}">Delete</a>
                        </div>
                    </td>
                  </tr>
{% endfor %}
                </tbody>
              </table>
            </div>
{% endblock content %}