wizello/core/urls.py
from django.urls import path, include
from .views import (
    DashboardView,
    IndexView)

app_name = 'core'

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name="home"),
    path('', include('django.contrib.auth.urls')),
    path('', IndexView.as_view(), name="index"),
]

wizello/request/api/urls.py
from django.urls import path
from .views import (
    RequestListAPIView,
    RequestAcceptAPIView,
    RequestDeleteAPIView,
)

urlpatterns = [
    path('', RequestListAPIView.as_view(), name="requestlistAPI"),
    path('accept/<int:pk>/', RequestAcceptAPIView.as_view(),
         name="requestacceptAPI"),
    path('delete/<int:pk>/', RequestDeleteAPIView.as_view(),
         name="requestdeleteAPI"),
]

wizello/request/urls.py
from django.urls import path, include
from .views import (
    RequestManagerListView, RequestManagerAcceptView,
    RequestListView, RequestCreateView, RequestDeleteView,
    RequestAdminListView, RequestAdminAcceptView)

app_name = 'request'

urlpatterns = [
    # request
    path('', RequestListView.as_view(), name="requestlist"),
    path('create/', RequestCreateView.as_view(), name="requestcreate"),
    path('delete/<int:pk>/', RequestDeleteView.as_view(), name="requestdelete"),
    # Manager
    path('manager/', RequestManagerListView.as_view(), name="requestmanagerlist"),
    path('manager/accept/<int:pk>/',
         RequestManagerAcceptView.as_view(), name="requestaccept"),
    # Admin
    path('admin/', RequestAdminListView.as_view(), name="requestadminlist"),
    path('admin/accept/<int:pk>/',
         RequestAdminAcceptView.as_view(), name="requestadminaccept"),
]

wizello/wizello/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('task/', include('task.urls')),
    path('request/', include('request.urls')),
    path('account/', include('account.urls')),
    path('organization/', include('organization.urls')),

    # API
    path('api/organization/', include('organization.api.urls')),
    path('api/employee/', include('account.api.urls')),
    path('api/task/', include('task.api.urls')),
    path('api/request/', include('request.api.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wizello/request/models.py
from core.models import BaseModel, models
from django.contrib.auth.models import User
from organization.models import Organization
from account.models import Employee


class Request(BaseModel):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    POSITION_TYPE = (
        ('M', "Manager"),
        ('EO', "Employee Organization"),
    )
    position = models.CharField(
        max_length=15, choices=POSITION_TYPE, default='EO')
    agreement = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Request"
        verbose_name_plural = "Requests"
        ordering = ['-created']

    def __str__(self):
        return "{} to {}".format(self.user.username, self.position)

    def get_request_status(self):
        if self.agreement:
            return "Verify"
        return "-"

wizello/request/api/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.utils import timezone
from rest_framework import generics
from rest_framework import permissions
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import RequestModelSerializer
from ..models import Request, Employee


class RequestListAPIView(generics.ListAPIView):
    serializer_class = RequestModelSerializer
    permission_classes = [permissions.IsAdminUser]

    def get_queryset(self):
        qs = Request.objects.filter(
            position="M").filter(user__employee__organization=None).filter(agreement=None)
        return qs


class RequestAcceptAPIView(APIView):
    permission_classes = (permissions.IsAdminUser,)

    def get(self, request, pk, format=None):
        obj_request = get_object_or_404(Request, pk=pk)
        obj_request.agreement = timezone.now()
        objEmployee = Employee.objects.get(user=obj_request.user)
        objEmployee.position = obj_request.position
        objEmployee.organization = obj_request.organization
        objEmployee.save()
        obj_request.save()
        message = "Change User Position"
        return Response({"message": message}, status=400)


class RequestDeleteAPIView(generics.DestroyAPIView):
    queryset = Request.objects.all()
    serializer_class = RequestModelSerializer
    permission_classes = [permissions.IsAdminUser]

wizello/request/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.views.generic import ListView, CreateView, View, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.urls import reverse_lazy
from django.db.models import Q
from .models import Request, User
from account.models import Employee

# -------------------- Request List


class RequestListView(LoginRequiredMixin, ListView):
    model = Request
    context_object_name = "requests"
    template_name = "request/requestlist.html"

    def get_queryset(self):
        qs = Request.objects.filter(
            user=self.request.user)
        return qs


class RequestCreateView(LoginRequiredMixin, CreateView):
    model = Request
    fields = ('organization', 'position')
    template_name = "core/formcreate.html"
    success_url = reverse_lazy("request:requestlist")

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class RequestDeleteView(LoginRequiredMixin, DeleteView):
    model = Request
    template_name = "core/confirm_delete.html"
    success_url = reverse_lazy("request:requestlist")

# -------------------- Request Manager List


class RequestManagerListView(LoginRequiredMixin, ListView):
    model = Request
    context_object_name = "requests"
    template_name = "request/requestmanagerlist.html"

    def get_queryset(self):
        organization = self.request.user.employee.organization
        qs = Request.objects.filter(
            organization=organization).exclude(user=self.request.user).exclude(Q(user__employee__organization=organization) | Q(position="M"))
        return qs


class RequestManagerAcceptView(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        obj_request = get_object_or_404(Request, pk=pk)
        obj_request.agreement = timezone.now()

        objEmployee = Employee.objects.get(user=obj_request.user)
        objEmployee.position = obj_request.position
        objEmployee.organization = obj_request.organization
        objEmployee.save()

        obj_request.save()
        return HttpResponseRedirect(reverse_lazy("request:requestmanagerlist"))


# -------------------- Request Admin List
class RequestAdminListView(LoginRequiredMixin, ListView):
    model = Request
    context_object_name = "requests"
    template_name = "request/requestadminlist.html"

    def get_queryset(self):
        qs = Request.objects.filter(
            position="M").filter(user__employee__organization=None).filter(agreement=None)
        return qs


class RequestAdminAcceptView(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        obj_request = get_object_or_404(Request, pk=pk)
        obj_request.agreement = timezone.now()

        objEmployee = Employee.objects.get(user=obj_request.user)
        objEmployee.position = obj_request.position
        objEmployee.organization = obj_request.organization
        objEmployee.save()

        obj_request.save()
        return HttpResponseRedirect(reverse_lazy("request:requestadminlist"))

wizello/request/templates/request/requestadminlist.html
{% extends "core/base.html" %}

{% block title %}Admin Requests{% endblock title %}

{% block content %}
<div class="card-header bg-transparent d-inline">
</div>
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Organization</th>
                    <th scope="col">User</th>
                    <th scope="col">Position</th>
                    <th scope="col">Act</th>
                  </tr>
                </thead>
                <tbody>

{% for obj_request in requests %}
    
                  <tr>
                    <th scope="row">
                        <span>{{obj_request.id}}</span>
                    </th>
                    <th scope="row">
                        <span>{{obj_request.organization.name}}</span>
                    </th>
                    <td>
                        <span>{{obj_request.user.username}}</span>
                    </td>
                    <td>
                        <span>{{obj_request.get_position_display}}</span>
                    </td>                    
                    <td>
                    {% if obj_request.agreement %}
                      <span>{{obj_request.agreement}}</span>
                    {% else %}
                        <div>
                            <a href="{% url 'request:requestadminaccept' obj_request.id %}">Active</a> / 
                            <a href="{% url 'request:requestdelete' obj_request.id %}">Delete</a>
                        </div>
                    {% endif %}
                    </td>
                  </tr>
{% endfor %}
                </tbody>
              </table>
            </div>
{% endblock content %}

wizello/request/templates/request/requestlist.html
{% extends "core/base.html" %}

{% block title %}Requests{% endblock title %}

{% block content %}
<div class="card-header bg-transparent d-inline">
    <a href="{% url 'request:requestcreate' %}" class="btn btn-info">Create New Request</a>
</div>
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Organization</th>
                    <th scope="col">User</th>
                    <th scope="col">Position</th>
                    <th scope="col">Act</th>
                  </tr>
                </thead>
                <tbody>

{% for obj_request in requests %}
    
                  <tr>
                    <th scope="row">
                        <span>{{obj_request.id}}</span>
                    </th>
                    <th scope="row">
                        <span>{{obj_request.organization.name}}</span>
                    </th>
                    <td>
                        <span>{{obj_request.user.username}}</span>
                    </td>
                    <td>
                        <span>{{obj_request.get_position_display}}</span>
                    </td>                    
                    <td>
                        <div>
                            <a href="{% url 'request:requestaccept' obj_request.id %}">Active</a> / 
                            <a href="{% url 'request:requestdelete' obj_request.id %}">Delete</a>
                        </div>
                    </td>
                  </tr>
{% endfor %}
                </tbody>
              </table>
            </div>
{% endblock content %}

wizello/request/templates/request/requestmanagerlist.html
{% extends "core/base.html" %}

{% block title %}Manager Requests{% endblock title %}

{% block content %}
<div class="card-header bg-transparent d-inline">
</div>
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Organization</th>
                    <th scope="col">User</th>
                    <th scope="col">Position</th>
                    <th scope="col">Act</th>
                  </tr>
                </thead>
                <tbody>

{% for obj_request in requests %}
    
                  <tr>
                    <th scope="row">
                        <span>{{obj_request.id}}</span>
                    </th>
                    <th scope="row">
                        <span>{{obj_request.organization.name}}</span>
                    </th>
                    <td>
                        <span>{{obj_request.user.username}}</span>
                    </td>
                    <td>
                        <span>{{obj_request.get_position_display}}</span>
                    </td>                    
                    <td>
                    {% if obj_request.agreement %}
                      <span>{{obj_request.agreement}}</span>
                    {% else %}
                        <div>
                            <a href="{% url 'request:requestaccept' obj_request.id %}">Active</a> / 
                            <a href="{% url 'request:requestdelete' obj_request.id %}">Delete</a>
                        </div>
                    {% endif %}
                    </td>
                  </tr>
{% endfor %}
                </tbody>
              </table>
            </div>
{% endblock content %}